Liquidity Manager
eco/eco-solver pull request #66
Opened 2024-12-06 06:33 UTC by carlosfebres

2024-12-18 21:49 UTC, StoyanD requested changes
Reviewed. Left most as comments. Would like you to also structure the liquidity folder the way the rest of the project is, particularly the bullmq/queue/processor objects should be outside that dir. also you need to add tests for all your services and logic

2024-12-18 21:49 UTC, StoyanD commented on src/liquidity-manager/utils/serialize.spec.ts
> +describe('Serialize BigInt', () => {
:)

2025-01-01 22:40 UTC, carlosfebres commented on src/liquidity-manager/utils/token.ts
> +      return balance.target - balance.current
Those values are BigInts and `Math.abs` doesn't support them

2025-01-01 23:55 UTC, carlosfebres commented on src/liquidity-manager/services/liquidity-manager.service.ts
> +    const surplusTokensTotal = getGroupTotal(sortedSurplusTokens)
I started to change this and realized that supporting tokens that are not 1-1 require non-trivial changes.

2025-01-02 00:00 UTC, carlosfebres commented on src/liquidity-manager/services/liquidity-provider-manager.service.ts
> +  async getQuote(
That's the intent. Choosing between liquidity providers will vary depending on the route so a switch/loop can't be added now.

2025-01-02 00:09 UTC, carlosfebres commented on src/liquidity-manager/jobs/check-balances-cron.job.ts
> +  static onFailed(job: LiquidityManagerJob, processor: LiquidityManagerProcessor, error: unknown) {
This function overwrites the parents method so params have to match

2025-01-02 00:11 UTC, carlosfebres commented on src/liquidity-manager/jobs/check-balances-cron.job.ts
> +  private static displayTokenTable(items: LiquidityManager.TokenDataAnalyzed[]) {
This is used to show what happens during job execution. If needed, we could also add this to the health endpoint.

2025-01-02 03:43 UTC, carlosfebres commented on src/liquidity-manager/queues/liquidity-manager.queue.ts
> +        defaultJobOptions: {
Why do the job options have to be part of the config? This seems like implementation logic.

2025-01-02 03:49 UTC, carlosfebres commented on src/liquidity-manager/liquidity-manager.module.ts
> +    LiquidityManagerQueue.initFlow(),
I think this should be ok. These static methods are part of the `LiquidityManagerQueue,` which only has logic to start the queue and start cron jobs.

2025-01-02 03:51 UTC, carlosfebres commented on src/liquidity-manager/jobs/check-balances-cron.job.ts
> +      removeOnComplete: true,
There should only be one `CHECK_BALANCES`. I've tested that when the job fails, it keeps running.

2025-01-02 03:52 UTC, carlosfebres commented on src/liquidity-manager/jobs/check-balances-cron.job.ts
> +    processor.logger.log('\n' + this.displayRebalancingTable(rebalances))
Wdym?

2025-01-02 03:53 UTC, carlosfebres commented on package.json
> +    "table": "^6.8.2",
This is used during run-time, so it should be part of the dependencies.

2025-01-02 03:55 UTC, carlosfebres commented on src/liquidity-manager/processors/grouped-jobs.processor.ts
> +export abstract class GroupedJobsProcessor<
No, but It will be used in the future to batch transaction execution jobs (doesn't exist yet).

2025-01-02 04:49 UTC, carlosfebres commented on src/liquidity-manager/services/liquidity-providers/LiFi/providers/evm/custom-evm-step-executor.ts
> +/* eslint-disable no-use-before-define */
I had to extract this from LiFi's SDK.

2025-01-02 04:50 UTC, carlosfebres commented on src/liquidity-manager/types/types.d.ts
> +  type TokenState = 'DEFICIT' | 'SURPLUS' | 'IN_RANGE'
Yes, enums couldn't be used from type definition files.

2025-01-02 16:11 UTC, StoyanD commented on src/liquidity-manager/utils/token.ts
> +      return balance.target - balance.current
lol, didnt know that, can add a util like
```
export class Mathb {
  static abs(x: bigint): bigint {
    return x < 0 ? -x : x;
  }
}
```

2025-01-02 16:18 UTC, StoyanD commented on src/liquidity-manager/types/types.d.ts
> +  type TokenState = 'DEFICIT' | 'SURPLUS' | 'IN_RANGE'
cant you define the type from the enum like so:
```
type TokenStateType = keyof typeof TokenState
```
that way you dont duplicate keys and risk forgetting to update both in the future

2025-01-02 16:32 UTC, StoyanD commented on src/liquidity-manager/queues/liquidity-manager.queue.ts
> +        defaultJobOptions: {
i usually run different job options in different environments. this allows me to connect to the redis clusters on. preprop/prod/staging and manipulate the tasks while debugging. if u look its already defined in the [eco configs](https://github.com/eco/eco-solver/blob/main/src/eco-configs/eco-config.types.ts#L73)

2025-01-02 16:35 UTC, StoyanD commented on src/liquidity-manager/services/liquidity-manager.service.ts
> +    const surplusTokensTotal = getGroupTotal(sortedSurplusTokens)
what do u mean? like u cant know the surplus you have if they are not usd based?

2025-01-02 16:37 UTC, StoyanD commented on src/liquidity-manager/services/liquidity-providers/LiFi/providers/evm/custom-evm-step-executor.ts
> +/* eslint-disable no-use-before-define */
if its not exported by their sdk, can u add a comment linking to the lifi sdk github for that file with its release/tag so we can track it and give credit to them?

2025-01-02 16:38 UTC, StoyanD commented on src/liquidity-manager/services/liquidity-providers/LiFi/providers/evm/custom-evm-step-executor.ts
> +/* eslint-disable no-use-before-define */
maybe u can even create a pr exporting it in their sdk if its public or leaving a request

2025-01-02 18:57 UTC, StoyanD commented on src/liquidity-manager/tests/liquidity-manager.service.spec.ts
> +        BullModule.registerFlowProducerAsync({ name: LiquidityManagerQueue.flowName }),
when i run these tests, it seems like the test are trying to connect to an actual redis. can u mock that out?
```
Ran all test suites matching /src\/liquidity-manager\/tests\/liquidity-manager.service.spec.ts/i.
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1610:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

2025-01-07 16:57 UTC, StoyanD commented on package.json
> +    "@eco-foundation/routes-ts": "beta",
actually need this to be set to `^0.1.10-beta`

2025-01-08 04:19 UTC, carlosfebres commented on src/liquidity-manager/types/types.d.ts
> +  type TokenState = 'DEFICIT' | 'SURPLUS' | 'IN_RANGE'
I don't think that'd be an issue, if an item in the enum doesn't match the TokenState type TypeScript will return an error.

2025-01-08 04:23 UTC, carlosfebres commented on src/transaction/smart-wallets/kernel/kernel-account-client-v2.service.ts
> +class KernelAccountClientV2ServiceBase<
It doesn't create the same wallet. It creates an instance of `KernelAccountClientV2`.

2025-01-08 04:29 UTC, carlosfebres commented on src/liquidity-manager/services/liquidity-providers/LiFi/providers/evm/custom-evm-step-executor.ts
> +/* eslint-disable no-use-before-define */
They released a new version with my changes to their SDK, so I'll remove this and just use their SDK

2025-01-08 16:38 UTC, StoyanD approved these changes

2025-01-08 16:41 UTC, merged